AllCops:
  TargetRubyVersion: 3.3
  SuggestExtensions: false

plugins:
  - rubocop-rails
  - rubocop-performance

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false