require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/welcome_lines", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # WelcomeLine. As you add validations to WelcomeLine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WelcomeLine.create! valid_attributes
      get welcome_lines_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      welcome_line = WelcomeLine.create! valid_attributes
      get welcome_line_url(welcome_line)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_welcome_line_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      welcome_line = WelcomeLine.create! valid_attributes
      get edit_welcome_line_url(welcome_line)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WelcomeLine" do
        expect {
          post welcome_lines_url, params: { welcome_line: valid_attributes }
        }.to change(WelcomeLine, :count).by(1)
      end

      it "redirects to the created welcome_line" do
        post welcome_lines_url, params: { welcome_line: valid_attributes }
        expect(response).to redirect_to(welcome_line_url(WelcomeLine.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WelcomeLine" do
        expect {
          post welcome_lines_url, params: { welcome_line: invalid_attributes }
        }.to change(WelcomeLine, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post welcome_lines_url, params: { welcome_line: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested welcome_line" do
        welcome_line = WelcomeLine.create! valid_attributes
        patch welcome_line_url(welcome_line), params: { welcome_line: new_attributes }
        welcome_line.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the welcome_line" do
        welcome_line = WelcomeLine.create! valid_attributes
        patch welcome_line_url(welcome_line), params: { welcome_line: new_attributes }
        welcome_line.reload
        expect(response).to redirect_to(welcome_line_url(welcome_line))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        welcome_line = WelcomeLine.create! valid_attributes
        patch welcome_line_url(welcome_line), params: { welcome_line: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested welcome_line" do
      welcome_line = WelcomeLine.create! valid_attributes
      expect {
        delete welcome_line_url(welcome_line)
      }.to change(WelcomeLine, :count).by(-1)
    end

    it "redirects to the welcome_lines list" do
      welcome_line = WelcomeLine.create! valid_attributes
      delete welcome_line_url(welcome_line)
      expect(response).to redirect_to(welcome_lines_url)
    end
  end
end
